name: Tests

on:
  push:

jobs:
  setup:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    name: Pest ${{ matrix.test-suite }}
    strategy:
      matrix:
        test-suite: ['phpcsfixer', 'phpstan', 'rector', 'phpcs']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: none
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3

      - name: Test php code
        run: vendor/bin/pest -p --testsuite ${{ matrix.test-suite }}
